server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  tracing:
    sampling:
    probability: 1.0

spring:
  output:
    ansi:
      enable: always
